@startuml
package [..] as C_0016431317663134048372 {
package [src] as C_0010634688166860467214 {
package [models] as C_0001626712604113445200 {
abstract "::IJsonSerializable" as C_0017605762593928520665
abstract C_0017605762593928520665 {
+~IJsonSerializable() = default : void
..
{abstract} +toJson() const = 0 : QJsonObject
__
}
enum "::ItemType" as C_0009506588567340924694
enum C_0009506588567340924694 {
WEAPON
ARMOR
ACCESSORY
RANDOM
}
abstract "::Item" as C_0005967165952864249862
abstract C_0005967165952864249862 {
+Item() : void
+Item(std::string_view name, std::string_view desc, int default_price, int add_price = 0) : void
+~Item() = default : void
..
+addToPrice(int add) : void
+getDesc() const : const std::string &
{abstract} +getItemType() const = 0 : ItemType
+getName() const : const std::string &
+getPrice() const : int
+getPriceModified() const : int
+getQualityPrice() const : int
+setDefaultDesc() : void
+setDefaultPrice() : void
+setDesc(std::string_view d) : void
+setName(std::string_view n) : void
+setQualityPrice(int q_price) : void
+toJson() const : QJsonObject
__
#_default_price : const int
#_desc : std::string
#_name : std::string
#_price : int
#_quality_price : int
}
class "::Weapon" as C_0009880302970961535201
class C_0009880302970961535201 {
+Weapon() : void
+Weapon(std::string_view name, std::string_view desc, int default_price, int price, WeaponType weapon_type, int dmg_desc, DMGType dmg_type, Attribute accuracy1, Attribute accuracy2, int accuracy_bonus, bool isSingleHanded, bool isRange, bool isMartial) : void
..
+getAccuracy1() const : Attribute
+getAccuracy2() const : Attribute
+getAccuracyBonus() const : int
+getDmgDesc() const : int
+getDmgType() const : DMGType
+getIsMartial() const : bool
+getIsRange() const : bool
+getIsSingleHanded() const : bool
+getItemType() const : ItemType
+getWeaponType() const : WeaponType
+setAccuracy1(Attribute a1) : void
+setAccuracy2(Attribute a2) : void
+setAccuracyBonus(int ab) : void
+setDmgDesc(int dd) : void
+setDmgType(DMGType dt) : void
+setIsMartial(bool im) : void
+setIsRange(bool ir) : void
+setIsSingleHanded(bool ish) : void
+setType(WeaponType t) : void
+toJson() const : QJsonObject
__
-_accuracy1 : Attribute
-_accuracy2 : Attribute
-_accuracy_bonus : int
-_dmg_desc : int
-_dmg_type : DMGType
-_isMartial : bool
-_isRange : bool
-_isSingleHanded : bool
-_weapon_type : WeaponType
}
class "::Accessory" as C_0001733752998306711321
class C_0001733752998306711321 {
+Accessory() = default : void
+Accessory(std::string_view name, std::string_view desc, int default_price, int price) : void
..
+getItemType() const : ItemType
+toJson() const : QJsonObject
__
}
class "::Armor" as C_0017091837617986840564
class C_0017091837617986840564 {
+Armor() : void
+Armor(std::string_view name, std::string_view desc, int default_price, int price, int initiative, bool isMartial, Attribute magic_defense, int magic_defense_bonus, Attribute defense, int defense_bonus, bool isShield) : void
..
+getDefAtr() const : Attribute
+getDefBonus() const : int
+getInitiative() const : int
+getIsMartial() const : bool
+getIsShield() const : bool
+getItemType() const : ItemType
+getMagDefAtr() const : Attribute
+getMagDefBonus() const : int
+setDef(int d) : void
+setInitiative(int in) : void
+setIsMartial(bool m) : void
+setIsShield(bool s) : void
+setMagDef(int md) : void
+toJson() const : QJsonObject
__
-_defense : Attribute
-_defense_bonus : int
-_initiative : int
-_isMartial : bool
-_isShield : bool
-_magic_defense : Attribute
-_magic_defense_bonus : int
}
}
package [core] as C_0009398224592071360425 {
class "::CampaignManager" as C_0006935415749788347394
class C_0006935415749788347394 {
+CampaignManager() = default : void
..
+addItem(std::unique_ptr<Item> item) : void
+addPlayer(std::unique_ptr<Player> player) : void
+clear() : void
+deleteAllItems() : void
+deleteAllPlayers() : void
+deleteItem(size_t idx) : void
+deletePlayer(size_t idx) : void
+getItem(size_t idx) const : Item &
+getItems() const : const std::vector<std::unique_ptr<Item>> &
+getPlayer(size_t idx) const : Player &
+getPlayers() const : const std::vector<std::unique_ptr<Player>> &
+getRandomPlayer() const : const Player &
+replaceItem(size_t idx, std::unique_ptr<Item> item) : void
+replacePlayer(size_t idx, std::unique_ptr<Player> player) : void
__
-_items : std::vector<std::unique_ptr<Item>>
-_players : std::vector<std::unique_ptr<Player>>
}
}
package [io] as C_0016395333381226012294 {
class "::JsonReader" as C_0002948440278719519756
class C_0002948440278719519756 {
{static} +loadItems(const QString & file_path, ItemType type) : std::vector<std::unique_ptr<Item>>
{static} +loadQualities(const QString & file_path) : std::vector<Quality>
{static} -parseArmor(const QJsonObject & JsonArmorObj, bool makeShield) : std::unique_ptr<Armor>
{static} -parseQuality(const QJsonObject & JsonQualityObj, bool makeOffensive) : Quality
{static} -parseWeapon(const QJsonObject & JsonWeaponObj) : std::unique_ptr<Weapon>
__
}
}
package [systems] as C_0016692703261607978348 {
abstract "::GeneratorStrategy" as C_0003391557478520177739
abstract C_0003391557478520177739 {
+~GeneratorStrategy() = default : void
..
{abstract} +generate(const Player & player) = 0 : std::unique_ptr<Item>
__
}
class "::QualityGenerator" as C_0017722926631985697211
class C_0017722926631985697211 {
+QualityGenerator(const QString & file_path) : void
..
+applyRandomQualityTo(Item * item) : void
+generate() : const Quality &
__
-_cache_qualities : std::vector<Quality>
}
class "::ItemGeneratorSystem" as C_0003751086353887321154
class C_0003751086353887321154 {
+ItemGeneratorSystem() : void
..
+assignQuality(ItemType type, Item * item) : void
+generateItem(ItemType type, const Player & player) : std::unique_ptr<Item>
{static} -getRandomItemType() : ItemType
{static} -isItemPriceValid(const Item & item, const Player & player) : bool
__
-quality_gen : std::map<ItemType,std::unique_ptr<QualityGenerator>>
-strategies : std::map<ItemType,std::unique_ptr<GeneratorStrategy>>
}
class "::AccessoryGenerator" as C_0004788119760935680862
class C_0004788119760935680862 {
+AccessoryGenerator() = default : void
..
+generate(const Player & player) : std::unique_ptr<Item>
__
}
class "::ArmorGenerator" as C_0005567866987455504025
class C_0005567866987455504025 {
+ArmorGenerator(const QString & file_path) : void
..
+generate(const Player & player) : std::unique_ptr<Item>
{static} -isArmorUsable(const Player & player, const Armor & armor) : bool
__
-_cache_armors : std::vector<std::unique_ptr<Armor>>
}
class "::WeaponGenerator" as C_0004150406585329947926
class C_0004150406585329947926 {
+WeaponGenerator(const QString & file_path) : void
..
-filterByPlayerAttributesHard(const Player & player) const : std::vector<const Weapon *>
-filterByPlayerAttributesSoft(const Player & player) const : std::vector<const Weapon *>
-filterByPlayerPreference(const Player & player) const : std::vector<const Weapon *>
+generate(const Player & player) : std::unique_ptr<Item>
{static} -isWeaponUsable(const Player & player, const Weapon & weapon) : bool
__
-_cache_weapons : std::vector<std::unique_ptr<Weapon>>
}
}
package [tests] as C_0009102687024667839383 {
class "::Test" as C_0002626979548338364165
class C_0002626979548338364165 {
+allArmorTests() : void
+allCostTests() : void
+allIGSTests() : void
+allWeaponTests() : void
-checkAttributes(const Weapon & w, const Player & p) : void
-checkCost(const Item & i) : void
-checkCostToLevel(const Item & i, const Player & p) : void
-checkMartial(const Weapon & w, const Player & p) : void
-checkMartial(const Armor & a) : void
-checkMartial(const Armor & a, const Player & p) : void
-checkPreference(const Weapon & w, const Player & p) : void
-checkRange(const Weapon & w, const Player & p) : void
-checkShield(const Armor & a, const Player & p) : void
-readArmor(const Armor & a) : void
-readWeapon(const Weapon & GenWeapon) : void
+testArmorPreferences() : void
+testArmorRandom() : void
+testIGSRandom() : void
+testIGSSpecific() : void
+testLegalArmorQuality() : void
+testWeaponAttributePreference() : void
+testWeaponFullPreferences() : void
+testWeaponRandom() : void
+testWeaponTypePreference() : void
__
-_ag : std::unique_ptr<ArmorGenerator>
-_igs : ItemGeneratorSystem
-_qg : std::unique_ptr<QualityGenerator>
-_wg : std::unique_ptr<WeaponGenerator>
-attributes : std::string[4]
-dmg_type : std::string[9]
-weapon_type : std::string[10]
}
}
}
}
C_0005967165952864249862 ..> C_0009506588567340924694
C_0017605762593928520665 <|-- C_0005967165952864249862
C_0009880302970961535201 ..> C_0009506588567340924694
C_0005967165952864249862 <|-- C_0009880302970961535201
C_0001733752998306711321 ..> C_0009506588567340924694
C_0005967165952864249862 <|-- C_0001733752998306711321
C_0017091837617986840564 ..> C_0009506588567340924694
C_0005967165952864249862 <|-- C_0017091837617986840564
C_0006935415749788347394 o-- C_0005967165952864249862 : -_items
C_0002948440278719519756 ..> C_0009880302970961535201
C_0002948440278719519756 ..> C_0017091837617986840564
C_0002948440278719519756 ..> C_0009506588567340924694
C_0002948440278719519756 ..> C_0005967165952864249862
C_0003391557478520177739 ..> C_0005967165952864249862
C_0017722926631985697211 ..> C_0005967165952864249862
C_0003751086353887321154 ..> C_0005967165952864249862
C_0003751086353887321154 o-- C_0009506588567340924694 : -strategies
C_0003751086353887321154 o-- C_0003391557478520177739 : -strategies
C_0003751086353887321154 o-- C_0009506588567340924694 : -quality_gen
C_0003751086353887321154 o-- C_0017722926631985697211 : -quality_gen
C_0004788119760935680862 ..> C_0005967165952864249862
C_0003391557478520177739 <|-- C_0004788119760935680862
C_0005567866987455504025 ..> C_0005967165952864249862
C_0005567866987455504025 o-- C_0017091837617986840564 : -_cache_armors
C_0003391557478520177739 <|-- C_0005567866987455504025
C_0004150406585329947926 ..> C_0005967165952864249862
C_0004150406585329947926 o-- C_0009880302970961535201 : -_cache_weapons
C_0003391557478520177739 <|-- C_0004150406585329947926
C_0002626979548338364165 ..> C_0009880302970961535201
C_0002626979548338364165 ..> C_0005967165952864249862
C_0002626979548338364165 ..> C_0017091837617986840564
C_0002626979548338364165 o-- C_0003751086353887321154 : -_igs
C_0002626979548338364165 o-- C_0004150406585329947926 : -_wg
C_0002626979548338364165 o-- C_0005567866987455504025 : -_ag
C_0002626979548338364165 o-- C_0017722926631985697211 : -_qg

'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
