@startuml
package [..] as C_0016431317663134048372 {
package [src] as C_0010634688166860467214 {
package [models] as C_0001626712604113445200 {
enum "::ItemType" as C_0009506588567340924694
enum C_0009506588567340924694 {
WEAPON
ARMOR
ACCESSORY
RANDOM
}
abstract "::Item" as C_0005967165952864249862
abstract C_0005967165952864249862 {
+Item() : void
+Item(std::string_view name, std::string_view desc, int default_price, int add_price) : void
+~Item() = default : void
..
+addToPrice(const int add) : void
+getDesc() const : const std::string &
{abstract} +getItemType() const = 0 : ItemType
+getName() const : const std::string &
+getPrice() const : int
+getPriceModified() const : int
+increasePriceBy(int add) : void
+setDefaultDesc() : void
+setDefaultPrice() : void
+setDesc(std::string_view d) : void
+setName(std::string_view n) : void
{abstract} +toJson() const = 0 : QJsonObject
__
#_default_price : const int
#_desc : std::string
#_name : std::string
#_price : int
}
enum "::Attribute" as C_0013522169845410927695
enum C_0013522169845410927695 {
WLP
INS
DEX
MIG
NONE
}
enum "::DMGType" as C_0009351376410296248543
enum C_0009351376410296248543 {
PHYSICAL
AIR
BOLT
DARK
EARTH
FIRE
ICE
LIGHT
POISON
NONE
}
enum "::WeaponType" as C_0008393046724430625929
enum C_0008393046724430625929 {
ARCANE
BOW
BRAWL
DAGGER
FIREARM
FLAIL
HEAVY
SPEAR
SWORD
THROWN
NONE
}
class "::Weapon" as C_0009880302970961535201
class C_0009880302970961535201 {
+Weapon() : void
+Weapon(std::string_view name, std::string_view desc, int default_price, int price, WeaponType weapon_type, int dmg_desc, DMGType dmg_type, Attribute accuracy1, Attribute accuracy2, int accuracy_bonus, bool isSingleHanded, bool isRange, bool isMartial) : void
..
+getAccuracy1() const : Attribute
+getAccuracy2() const : Attribute
+getAccuracyBonus() const : int
+getDmgDesc() const : int
+getDmgType() const : DMGType
+getIsMartial() const : bool
+getIsRange() const : bool
+getIsSingleHanded() const : bool
+getItemType() const : ItemType
+getWeaponType() const : WeaponType
+setAccuracy1(Attribute a1) : void
+setAccuracy2(Attribute a2) : void
+setAccuracyBonus(int ab) : void
+setDmgDesc(int dd) : void
+setDmgType(DMGType dt) : void
+setIsMartial(bool im) : void
+setIsRange(bool ir) : void
+setIsSingleHanded(bool ish) : void
+setType(WeaponType t) : void
+toJson() const : QJsonObject
__
-_accuracy1 : Attribute
-_accuracy2 : Attribute
-_accuracy_bonus : int
-_dmg_desc : int
-_dmg_type : DMGType
-_isMartial : bool
-_isRange : bool
-_isSingleHanded : bool
-_weapon_type : WeaponType
}
}
package [io] as C_0016395333381226012294 {
class "::JsonReader" as C_0002948440278719519756
class C_0002948440278719519756 {
{static} +loadItems(const QString & file_path, ItemType type) : std::vector<std::unique_ptr<Item>>
{static} +loadQualities(const QString & file_path) : std::vector<Quality>
{static} -parseArmor(const QJsonObject & JsonArmorObj, bool makeShield) : std::unique_ptr<Armor>
{static} -parseQuality(const QJsonObject & JsonQualityObj, bool makeOffensive) : Quality
{static} -parseWeapon(const QJsonObject & JsonWeaponObj) : std::unique_ptr<Weapon>
__
}
}
package [systems] as C_0016692703261607978348 {
class "::WeaponGenerator" as C_0004150406585329947926
class C_0004150406585329947926 {
+WeaponGenerator(const std::string & file_path) : void
..
-filterByPlayerAttributesHard(const Player & player) const : std::vector<const Weapon *>
-filterByPlayerAttributesSoft(const Player & player) const : std::vector<const Weapon *>
-filterByPlayerPreference(const Player & player) const : std::vector<const Weapon *>
+generate(const Player & player) : std::unique_ptr<Item>
{static} -isWeaponUsable(const Player & player, const Weapon & weapon) : bool
__
-_cache_weapons : std::vector<std::unique_ptr<Weapon>>
}
}
package [tests] as C_0009102687024667839383 {
class "::Test" as C_0002626979548338364165
class C_0002626979548338364165 {
+allArmorTests() : void
+allCostTests() : void
+allIGSTests() : void
+allWeaponTests() : void
-checkAttributes(const Weapon & w, const Player & p) : void
-checkCost(const Item & i) : void
-checkCostToLevel(const Item & i, const Player & p) : void
-checkMartial(const Weapon & w, const Player & p) : void
-checkMartial(const Armor & a) : void
-checkMartial(const Armor & a, const Player & p) : void
-checkPreference(const Weapon & w, const Player & p) : void
-checkRange(const Weapon & w, const Player & p) : void
-checkShield(const Armor & a, const Player & p) : void
-readArmor(const Armor & a) : void
-readWeapon(const Weapon & GenWeapon) : void
+testArmorPreferences() : void
+testArmorRandom() : void
+testIGSRandom() : void
+testIGSSpecific() : void
+testLegalArmorQuality() : void
+testWeaponAttributePreference() : void
+testWeaponFullPreferences() : void
+testWeaponRandom() : void
+testWeaponTypePreference() : void
__
-_ag : std::unique_ptr<ArmorGenerator>
-_igs : ItemGeneratorSystem
-_qg : std::unique_ptr<QualityGenerator>
-_wg : std::unique_ptr<WeaponGenerator>
-attributes : std::string[4]
-dmg_type : std::string[9]
-weapon_type : std::string[10]
}
}
}
}
C_0005967165952864249862 ..> C_0009506588567340924694
C_0009880302970961535201 ..> C_0009506588567340924694
C_0009880302970961535201 o-- C_0008393046724430625929 : -_weapon_type
C_0009880302970961535201 o-- C_0009351376410296248543 : -_dmg_type
C_0009880302970961535201 o-- C_0013522169845410927695 : -_accuracy1
C_0009880302970961535201 o-- C_0013522169845410927695 : -_accuracy2
C_0005967165952864249862 <|-- C_0009880302970961535201
C_0002948440278719519756 ..> C_0009880302970961535201
C_0002948440278719519756 ..> C_0009506588567340924694
C_0002948440278719519756 ..> C_0005967165952864249862
C_0004150406585329947926 ..> C_0005967165952864249862
C_0004150406585329947926 o-- C_0009880302970961535201 : -_cache_weapons
C_0002626979548338364165 ..> C_0009880302970961535201
C_0002626979548338364165 ..> C_0005967165952864249862
C_0002626979548338364165 o-- C_0004150406585329947926 : -_wg

'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
